/*/////////////////////////////////////
// Error case: cyclic dependency

MESSAGE PROTO=JSON,GMQ NONEXTENDABLE base {
  STRUCT cyclic_1 c;
};

STRUCT cyclic_1 {
	STRUCT cyclic_2 d;
};

STRUCT cyclic_2 {
	STRUCT cyclic_1 e;
};
///////////////////////////////////*/

MESSAGE PROTO = JSON, GMQ point32_alias = STRUCT point3D;


MESSAGE PROTO = JSON LevelTraceData{
	STRUCT CharacterParam CharacterParam;
	VECTOR<STRUCT POINT3DREAL> Points;
};

STRUCT CharacterParam{
	INTEGER ID;
	STRUCT Size Size;
};

STRUCT Size{
  REAL X;
  REAL Y;
  REAL Z;
};

STRUCT POINT3DREAL{
  REAL X;
  REAL Y;
  REAL Z;
};

MESSAGE PROTO = JSON, GMQ PolygonSt{
	VECTOR<STRUCT PolygonMap> polygonMap;
	VECTOR<STRUCT PolygonMap> concaveMap;
	VECTOR<STRUCT ObstacleMap> obstacleMap;
	VECTOR<STRUCT LineMap> portalMap;
	VECTOR<STRUCT LineMap> jumpMap;
	REAL polygonSpeed;
};

STRUCT LineMap{
	VECTOR<STRUCT Line> LineMap;
};

STRUCT Line{
	VECTOR<STRUCT NONEXTENDABLE Vertex> a;
	VECTOR<STRUCT NONEXTENDABLE Vertex> b;
};

STRUCT ObstacleMap{
	VECTOR<STRUCT PolygonMap> ObstacleMap;
};

STRUCT PolygonMap{
	VECTOR<STRUCT NONEXTENDABLE Vertex> PolygonMap;
};

STRUCT NONEXTENDABLE Vertex{
  INTEGER x;
  INTEGER y;
  INTEGER z;
};



STRUCT NONEXTENDABLE point {
  INTEGER x;
  INTEGER y;
};

STRUCT point3D {
  INTEGER x;
  INTEGER y;
  INTEGER z;
};


MESSAGE PROTO=JSON,GMQ message_one {
  INTEGER firstParam;
  VECTOR<INTEGER> secondParam;
  VECTOR<STRUCT point3D> thirdParam;
  UINTEGER forthParam;
  CHARACTER-STRING fifthParam;
  VECTOR<STRUCT NONEXTENDABLE point> sixthParam;
  REAL seventhParam;
  STRUCT NONEXTENDABLE point eighthParam;
  STRUCT point3D ninethParam;
};

MESSAGE PROTO=JSON,GMQ NONEXTENDABLE point {
  STRUCT point point;
};

MESSAGE PROTO=JSON,GMQ NONEXTENDABLE point3D {
  STRUCT point3D pt;
};


