/*/////////////////////////////////////
// Error case: cyclic dependency

MESSAGE SCOPE:ID=123 PROTO=JSON,GMQ NONEXTENDABLE base {
  STRUCT cyclic_1 c;
};

STRUCT cyclic_1 {
	STRUCT cyclic_2 d;
};

STRUCT cyclic_2 {
	STRUCT cyclic_1 e;
};
///////////////////////////////////*/

MESSAGE PROTO = JSON, GMQ scope_one:point32_alias=1 = STRUCT point3D;


MESSAGE PROTO = JSON level_trace:LevelTraceData=1{
	STRUCT CharacterParam CharacterParam;
	VECTOR<STRUCT POINT3DREAL> Points;
};

STRUCT CharacterParam{
	INTEGER ID;
	STRUCT Size Size;
};

STRUCT Size{
  REAL X;
  REAL Y;
  REAL Z;
};

STRUCT POINT3DREAL{
  REAL X;
  REAL Y;
  REAL Z;
};

MESSAGE PROTO = JSON, GMQ infrastructural:PolygonSt=2{
	VECTOR<STRUCT PolygonMap> polygonMap;
	VECTOR<STRUCT PolygonMap> concaveMap;
	VECTOR<STRUCT ObstacleMap> obstacleMap;
	VECTOR<STRUCT LineMap> portalMap;
	VECTOR<STRUCT LineMap> jumpMap;
	REAL polygonSpeed;
};

STRUCT LineMap{
	VECTOR<STRUCT Line> LineMap;
};

STRUCT Line{
	VECTOR<STRUCT NONEXTENDABLE Vertex> a;
	VECTOR<STRUCT NONEXTENDABLE Vertex> b;
};

STRUCT ObstacleMap{
	VECTOR<STRUCT PolygonMap> ObstacleMap;
};

STRUCT PolygonMap{
	VECTOR<STRUCT NONEXTENDABLE Vertex> PolygonMap;
};

STRUCT NONEXTENDABLE Vertex{
  INTEGER x;
  INTEGER y;
  INTEGER z;
};



STRUCT NONEXTENDABLE point {
  INTEGER x;
  INTEGER y;
};

STRUCT point3D {
  INTEGER x;
  INTEGER y;
  INTEGER z;
};


MESSAGE PROTO=JSON,GMQ infrastructural:message_one=3 {
  INTEGER firstParam;
  VECTOR<INTEGER> secondParam;
  VECTOR<STRUCT point3D> thirdParam;
  UINTEGER forthParam;
  CHARACTER-STRING fifthParam;
  VECTOR<STRUCT NONEXTENDABLE point> sixthParam;
  REAL seventhParam;
  STRUCT NONEXTENDABLE point eighthParam;
  STRUCT point3D ninethParam;
};

MESSAGE PROTO=JSON,GMQ NONEXTENDABLE infrastructural:point=4 {
  STRUCT point point;
};

MESSAGE PROTO=JSON,GMQ NONEXTENDABLE infrastructural:point3D=5 {
  STRUCT point3D pt;
};


