
SCOPE test_gmq PROTO = GMQ;
SCOPE test_json PROTO = JSON;

MESSAGE test_gmq:point3D_alias=1 = STRUCT point3D;
MESSAGE test_json:point_alias=2 = STRUCT point;

STRUCT NONEXTENDABLE point {
  INTEGER x;
  INTEGER y;
};

STRUCT point3D {
  INTEGER x;
  INTEGER y;
  INTEGER z;
};

STRUCT message_one {
  INTEGER firstParam;
  VECTOR<INTEGER> secondParam;
  VECTOR<STRUCT point3D> thirdParam;
  UINTEGER forthParam;
  CHARACTER-STRING fifthParam;
  VECTOR<STRUCT NONEXTENDABLE point> sixthParam;
  REAL seventhParam;
  STRUCT NONEXTENDABLE point eighthParam;
  STRUCT point3D ninethParam;
  VECTOR<REAL> tenthParam;
};

MESSAGE test_gmq:message_one_gmq=1 = STRUCT message_one;
MESSAGE test_json:message_one_json=2 = STRUCT message_one;

