

/*MESSAGE message_one {
  enum EnumSecond {s_first=0,s_second=1, s_third=2} enum_second;
  
  INTEGER ir_first;
  UINTEGER uir_second;
  
  INTEGER DEFAULT = -1986 ir_third;
  UINTEGER DEFAULT = 1984 uir_forth;
  
  INTEGER[-10,10] ir_fifth;
  UINTEGER[30,100] uir_fifth;
  
  INTEGER[-10,10] DEFAULT = 4 ir_sixth;
  UINTEGER[30,100] DEFAULT = 34 uir_seventh;
  
  INTEGER[,10] ir_fifth_2;
  UINTEGER[,100] uir_fifth_2;
  
  INTEGER[-10,] DEFAULT = 4 ir_sixth_2;
  UINTEGER[30,] DEFAULT = 34 uir_seventh_2;
  
  BYTE_ARRAY[16] ba_nonce;
  
  CHARACTER-STRING string_str_1;
  CHARACTER-STRING DEFAULT = "ABCD" string_str_3;
  CHARACTER-STRING MAX_LENGTH = 17 string_str_2;
  CHARACTER-STRING MAX_LENGTH = 19 DEFAULT = "ABCD" string_str_4;
  CHARACTER-STRING DEFAULT = "ABCD" MAX_LENGTH = 20 string_str_5;
  
  BLOB blob;
};*/

/*MESSAGE PROTO=JSON,GMQ message_one {
//  enum EnumSecond {s_first=0,s_second=1, s_third=2} enum_first;
//  enum EnumSecond {s_first=0,s_second=1, s_third=2} DEFAULT = s_second enum_second;

  INTEGER ir_first_in_msg_1;
  UINTEGER uir_second;
  
  INTEGER DEFAULT = -1986 ir_third;
  UINTEGER DEFAULT = 1984 uir_forth;
  
  CHARACTER-STRING string_str_1;
  CHARACTER-STRING DEFAULT = "ABCD" string_str_3;
};


MESSAGE PROTO=JSON message_two {

  INTEGER ir_first;
  UINTEGER uir_second_in_msg_2;
  
  INTEGER DEFAULT = -1986 ir_third;
  UINTEGER DEFAULT = 1984 uir_forth;
  
  CHARACTER-STRING string_str_1;
  CHARACTER-STRING DEFAULT = "EFGH" string_str_3;
};*/

MESSAGE PROTO=JSON,GMQ message_one {
  INTEGER DEFAULT = 10 firstParam;
  CHARACTER-STRING DEFAULT = "default_v" secondParam;
  UINTEGER DEFAULT = 30 thirdParam;
  VECTOR<MESSAGE NONEXTENDABLE point> vec;
};

MESSAGE PROTO=JSON,GMQ NONEXTENDABLE point {
  INTEGER x;
  INTEGER y;
};

